### ISSUE TITLE
Nicer front page

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/schemas#2]
Now that this repository is live, we should add some information on the front page: http://schemas.optimade.org

E.g., linking to https://www.optimade.org, explaining that this domain is used for our certificate permalinks, and explaining that our current OpenAPI schemas are located under http://schemas.optimade.org/openapi/<major version>.<minor version>/optimade.json and optimade_index.json respectively.

**Comment by ml-evs** [comment]
Given the lack of activity and very low bar, I just committed some changes directly to the repo that improve the front page, which I think closes this issue...
